variables:
  APP_NAME: "th2-hand"
  MAJOR_VERSION: "1"
  MINOR_VERSION: "1"
  MAINTENANCE_VERSION: "63"
  INSPECTION_ENABLED: 'true'
  TEST_ENABLED: 'false'
  ARTIFACTORY_PUBLISH: 'true'

include:
  - project: 'vivarium/th2/pipelines'
    ref: master
    file: '/.gitlab-ci-java.yml'
