name: Build and publish jar to sonatype snapshot repository

on:
  push:
    branches-ignore:
      - master
      - version-*
      - dependabot*
    paths-ignore:
      - README.md

jobs:
  build-job:
    uses: th2-net/.github/.github/workflows/compound-java-dev.yml@main
    with:
      build-target: 'Sonatype,Docker'
      docker-username: ${{ github.actor }}
    secrets:
      docker-password: ${{ secrets.GITHUB_TOKEN }}
      sonatypeUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
      sonatypePassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
      sonatypeSigningKey: ${{ secrets.SONATYPE_GPG_ARMORED_KEY }}
      sonatypeSigningPassword: ${{ secrets.SONATYPE_SIGNING_PASSWORD }}